### ISSUE TITLE
/usr/bin/ld: 找不到 -linotify

### ISSUE THREAD

**Issue by 331527583** [nebula-im/seqsvr#2]
我在ubuntu14.04上，我所用的g++-5.4.1版本（为了支持c++11或c++14特性）。当我在make seqsvr时候，ld找不到linotify，请问有解决此问题建议嘛？是否支持ubuntu平台？谢谢
$ make 
[ 26%] Built target base
[ 58%] Built target net
[ 65%] Built target mysql_client
[ 68%] Built target redis_client
Linking CXX executable ../bin/client
/usr/bin/ld: 找不到 -linotify
collect2: error: ld returned 1 exit status
make[2]: *** [bin/client] 错误 1
make[1]: *** [client/CMakeFiles/client.dir/all] 错误 2
make: *** [all] 错误 2
cxh@cxh:~/work/seqsvr/build$ vim Makefile 
cxh@cxh:~/work/seqsvr/build$

**Comment by wubenqi** [comment]
已经修复。

**Comment by wubenqi** [comment]
谢谢关注，欢迎多提意见。

**Comment by 331527583** [comment]
我发现在linux2.6.13内核后，inotify已经集成进内核。所以，我在CMakeLists.txt 去掉inotify库链接。
