### ISSUE TITLE
有关mediatesvr如何向storesvr写路由表的疑惑

### ISSUE THREAD

**Issue by 331527583** [nebula-im/seqsvr#4]
【疑惑】在设计实现中阐述到，mediate服务会获得alloc服务状态（目前代码中似乎还没有实现），然后向store中更新路由表信息（ip+port）。那么，mediate服务是通过注册http_client服务，通过http服务向mediate报告自身状态信息？还是mediate上注册的http_server服务主动获得alloc服务状态的？
另外，如果mediate不能获得alloc状态，那么就不能更新storesvr上的路由表信息，那么最终client获得不到路由表信息，并且也获得不到sequence信息，那是不是目前分布式部署方案，还不能正常工作？

**Comment by 331527583** [comment]
// 客户端连接服务
  RegisterService("mediate_server", "http_server", "http");
  RegisterService("store_client", "rpc_client", "zrpc");
  BaseServer::Initialize();

此处注册一个mediate_server服务，一个store_client服务。请问store_client服务用于向storesvr更新路由表么

**Comment by wubenqi** [comment]
store_client是向storesvr更新路由表。
