### ISSUE TITLE
请问使用的thrift版本是什么？

### ISSUE THREAD

**Issue by tangxy** [nebula-im/seqsvr#5]
你好，我现在在14.04.1-Ubuntu  gcc version 5.4.1 20160904  环境下使用 fbthrift-2017.05.15.00 编译，
make install fbthrift-2017.05.15.00  会报错。  手工拷贝头文件到 /usr/local/include/thrift 也不行。

**Comment by wubenqi** [comment]
我用的是这个版本，比较新的。
commit 6ef23bae9702796ab77641ceda33ff9df89fdf59 (HEAD -> master, origin/master, origin/HEAD)
Author: Laurie Clark-Michalek <lcm@fb.com>
Date:   Thu Aug 31 20:00:15 2017 -0700
