### ISSUE TITLE
CheckIDByRange 判断咨询

### ISSUE THREAD

**Issue by tangxy** [nebula-im/seqsvr#6]
section.h  第 115 的函数
inline bool CheckIDByRange(RangeID range, uint32_t id) {
  return id>=range.id_begin && id<range.size+id;
}

应该是：
inline bool CheckIDByRange(RangeID range, uint32_t id) {
  return id>=range.id_begin && id<range.size+range.id_begin;
}
吧？

**Comment by wubenqi** [comment]
是的。非常感谢，我这就改掉。
