### ISSUE TITLE
替换thrift版本0.9.2版本

### ISSUE THREAD

**Issue by tangxy** [nebula-im/seqsvr#7]
介于公司内部使用软件库原因，我将这个版本中的nebula 和 folly库做了剔除，并将thrift版本替换成0.9.2。 同时封装了C++和JAVA的客户端现在代码和自测已完成， 请问这样的代码是否可以反馈到这个里面。

**Comment by wubenqi** [comment]
可以啊

**Comment by wubenqi** [comment]
我帮你开个提交权限吧，我也考虑过去掉folly和nebula的依赖。
